<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0-ios</TargetFramework>
        <SupportedOSPlatformVersion>14.0</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <UseInterpreter>true</UseInterpreter>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AppIcon>AppIcon</AppIcon>
        <RunPostBuildEvent>Always</RunPostBuildEvent>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <CodesignKey>iPhone Developer</CodesignKey>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.iOS"/>
    </ItemGroup>

    <ItemGroup>
        <NativeReference Include="melondsds_libretro.framework">
            <Kind>Framework</Kind>
            <SmartLink>False</SmartLink>
            <ForceLoad>True</ForceLoad>
        </NativeReference>
    </ItemGroup>

    <ItemGroup>
        <None Update="Info.plist" PublishFolderType="None" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AvFoundationBackend\AvFoundationBackend.csproj" />
        <ProjectReference Include="..\ITDSWrapper\ITDSWrapper.csproj"/>
    </ItemGroup>
</Project>
