#!/bin/sh

DIR=$(dirname "$0")
ARM64=$(sysctl -ni hw.optional.arm64)

if [[ "$ARM64" == 1 ]]; then
    exec "$DIR/SteamworksHelper.ARM64.app/Contents/MacOS/SteamworksHelper"
else
    exec "$DIR/SteamworksHelper.X64.app/Contents/MacOS/SteamworksHelper"
fi