//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITDSWrapper.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITDSWrapper.Assets.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Into the Dream Spring.
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal (Bottom on Right).
        /// </summary>
        public static string ScreenLayoutLeftRight {
            get {
                return ResourceManager.GetString("ScreenLayoutLeftRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal (Bottom on Left).
        /// </summary>
        public static string ScreenLayoutRightLeft {
            get {
                return ResourceManager.GetString("ScreenLayoutRightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string ScreenLayoutTopBottom {
            get {
                return ResourceManager.GetString("ScreenLayoutTopBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility Settings.
        /// </summary>
        public static string SettingsAccessibility {
            get {
                return ResourceManager.GetString("SettingsAccessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        public static string SettingsAccessibilityHeader {
            get {
                return ResourceManager.GetString("SettingsAccessibilityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Game.
        /// </summary>
        public static string SettingsBackToGame {
            get {
                return ResourceManager.GetString("SettingsBackToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Borders.
        /// </summary>
        public static string SettingsBorders {
            get {
                return ResourceManager.GetString("SettingsBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Settings.
        /// </summary>
        public static string SettingsController {
            get {
                return ResourceManager.GetString("SettingsController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string SettingsControllerHeader {
            get {
                return ResourceManager.GetString("SettingsControllerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string SettingsDiscord {
            get {
                return ResourceManager.GetString("SettingsDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        public static string SettingsDisplay {
            get {
                return ResourceManager.GetString("SettingsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string SettingsDisplayHeader {
            get {
                return ResourceManager.GetString("SettingsDisplayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string SettingsLegal {
            get {
                return ResourceManager.GetString("SettingsLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Survey.
        /// </summary>
        public static string SettingsPlayerSurvey {
            get {
                return ResourceManager.GetString("SettingsPlayerSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit to Desktop.
        /// </summary>
        public static string SettingsQuitToDesktop {
            get {
                return ResourceManager.GetString("SettingsQuitToDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Layout.
        /// </summary>
        public static string SettingsScreenLayout {
            get {
                return ResourceManager.GetString("SettingsScreenLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Reader.
        /// </summary>
        public static string SettingsScreenReader {
            get {
                return ResourceManager.GetString("SettingsScreenReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string SettingsWebsite {
            get {
                return ResourceManager.GetString("SettingsWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string SettingSwitchDisabled {
            get {
                return ResourceManager.GetString("SettingSwitchDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string SettingSwitchEnabled {
            get {
                return ResourceManager.GetString("SettingSwitchEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string SettingSwitchOff {
            get {
                return ResourceManager.GetString("SettingSwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string SettingSwitchOn {
            get {
                return ResourceManager.GetString("SettingSwitchOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless.
        /// </summary>
        public static string WindowStateBorderless {
            get {
                return ResourceManager.GetString("WindowStateBorderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string WindowStateFullScreen {
            get {
                return ResourceManager.GetString("WindowStateFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowing Mode.
        /// </summary>
        public static string WindowStateSettingsLabel {
            get {
                return ResourceManager.GetString("WindowStateSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        public static string WindowStateWindowed {
            get {
                return ResourceManager.GetString("WindowStateWindowed", resourceCulture);
            }
        }
    }
}
